version: 0.2
            
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run-script build
artifacts:
  files:
    - '**/*'
  name: portfolio-site-$(AWS_REGION)-$(date +%Y-%m-%d) 
  base-directory: build